# Generated by Django 4.2.2 on 2023-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Star",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=20)),
                ("book_id", models.CharField(max_length=20)),
            ],
        ),
    ]
