# Generated by Django 4.2.2 on 2023-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("chapter_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_id", models.IntegerField(default=0)),
                ("chapter_no", models.IntegerField(default=0)),
                ("chapter_name", models.CharField(max_length=100)),
                ("chapter_href", models.CharField(max_length=100)),
            ],
        ),
    ]
