# Generated by Django 4.2.2 on 2023-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("book_id", models.IntegerField()),
                ("chapter_id", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("range1", models.CharField(max_length=255)),
                ("note", models.CharField(max_length=255)),
                ("cfi", models.CharField(max_length=255)),
            ],
        ),
    ]
