# Generated by Django 4.2.2 on 2023-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=20)),
                ("ifManager", models.BooleanField()),
            ],
        ),
    ]
